server.port=8080
spring.application.name=gateway-service

# Actuator
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always

# App info
app.version=1.0.0
app.environment=${APP_ENV:local}
