pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                echo 'Code checkout done by Jenkins job'
            }
        }

        stage('Maven Build & test') {
            steps {
            dir('eks-microservice/gateway-service'){
                sh 'mvn clean test package'
            }
            }
            post{
                always{
                    junit 'eks-microservice/gateway-service/target/surefire-reports/*.xml'
                }
            }
        }

        stage('Docker Build') {
            steps {
                dir('eks-microservice/gateway-service'){
                sh 'docker build -t gateway-service:jenkins .'
            }
            }
        }

        stage('Health Test') {
            steps {
                sh '''
                    docker rm -f gateway-service-test || true
                    docker run -d --name gateway-service-test -p 8081:8080 gateway-service:jenkins
                    sleep 40
                    #docker exec gateway-service-test curl http://localhost:8081/actuator/health
                    docker exec gateway-service-test wget -qO- http://localhost:8080/actuator/health
                    docker rm -f gateway-service-test
                '''
            }
        }
    }
}
